apiVersion: v1 
kind: Pod
metadata: 
  name: roboshop-env
  labels:
    project: roboshop-env
    purpose: practice
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: COURSE 
      value: "Devops"