apiVersion: v1 
kind: Pod
metadata:
  name: pod-configmap
  labels:
   project: configmap-pod
   purpose: pod-configmap-linking
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: configmap