apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  spec:
    selector:
      project: service-demo
      environment: dev
      purpose: practice
    ports:
      - protocol: TCP
        port: 80 # service port
        targetPort: 80 # container port

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-service
  labels:
    project: service-demo
    environment: dev
    purpose: practice
spec:
  containers:
  - name: nginx
    image: nginx

