apiVersion: v1
kind: Service
metadata: 
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    project: roboshop-nodeport
    purpose: practice-np
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx-nodeport
  labels:
    project: roboshop-nodeport
    purpose: practice-np
spec:
  containers:
  - name: nginx
    image: nginx