apiVersion: v1
kind: Service
metadata: 
  name: nginx-nodeport
spec:
  selector:
    project: roboshop-nodeport
    purpose: practice-np
  ports:
  - port: 


---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx-nodeport
  labels:
    project: roboshop-nodeport
    purpose: practice-np
spec:
  containers:
  - name: nginx
    iamge: nginx