apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
spec:
  type: LoadBalancer
  selector:
    project: roboshop-lb
    purpose: practice-lb
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-loadbalancer
  labels:
    project: roboshop-lb
    purpose: practice-lb
spec:
  containers:
  - name: nginx
    image: nginx