apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs 
  # replica set labels
  labels:
    purpose: replicas
    project: roboshop-rs
spec:
  replicas: 3
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector: 
    matchLabels:
      purpose: replicas
      project: roboshop-rs
  # This is pod definition
  template:
    metadata:
      labels:
        purpose: replicas
        project: roboshop-rs
    spec:
      containers:
      - name: nginx
        #image: nginx:stable-perl
        image: nginx