apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
  labels:
    project: roboshop-deployment
    purpose: practice-de
spec:
  replicas: 3
  selector:
    matchLabels:
      project: roboshop-deployment
      purpose: practice-de
  template:
    metadata:
      name: pod-deployment
      labels:
        project: roboshop-deployment
        purpose: practice-de
    spec:
      containers:
      - name: nginx
        image: nginx:latest
