apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic-pvc
spec:
  storageClassName: roboshop-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-dynamic-pod
  labels:
    project: roboshop
    purpose: ebs-dynamic-demo
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage-dynamic
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage-dynamic
    persistentVolumeClaim:
      claimName: ebs-dynamic-pvc