apiVersion : v1 
kind: PersistentVolume
metadata:
  name: efs-static-pv
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-056b58f2132fc9960
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: efs-static-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
--- 
apiVersion: v1
kind: Pod
metadata:
  name: efs-static-pod
  labels:
    project: roboshop
    purpose: efs-static-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage-efs
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage-efs
    persistentVolumeClaim:
      claimName: efs-static-pvc
---
apiVersion: v1 
kind: Service
metadata:
  name: efs-static-service
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    purpose: efs-static-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
