apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-pvc
spec:
  storageClassName: "efs-storageclass-dynamic"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1 
kind: Pod
metadata:
  name: efs-dynamic-pod
  labels:
    project: roboshop 
    purpose: efs-dynamic-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-dynamic-pvc
---
apiVersion: v1 
kind: Service
metadata:
  name: efs-dynamic-service
spec:
  type: LoadBalancer
  selector:
    project: roboshop 
    purpose: efs-dynamic-pod
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port